---
title: "SF Bikeshare"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(scales)
library(plotly)

## ged data 
trips_df <- read_csv('http://s3.amazonaws.com/assets.datacamp.com/production/course_6355/datasets/sanfran_bikeshare_joined_oneday.csv')


```

Overview
===================================================================

Column {data-width=350}
-----------------------------------------------------------------------

### Scorecard

```{r}
num_trips <- nrow(trips_df)

valueBox(prettyNum(num_trips, big.mark=','),
         href='#trends')

```

### Trips Percent

```{r}

short_trips <- sum(trips_df$duration_sec < 600) # under 10 min
pct_short_trips <- round(100 * short_trips / num_trips, 0)

gauge(value=pct_short_trips,
      min=0,
      max=100,
      sectors=gaugeSectors(
        success=c(70,100),
        warning=c(33,69),
        danger=c(0,32)
        ),
      symbol='%'
      )
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

Trends
=========================================================

### Trips by Starting Hour

```{r}
trips_df_clean <- data.frame(trips_df)
#trips_df_clean$start_date <- date(trips_df_clean$start_date)
trips_df_clean <- trips_df_clean %>% mutate(
  start_hr=hour(trips_df_clean$start_date)
)
trips_df_hr <- trips_df_clean %>% group_by(start_hr) %>% summarize(num_trips=n())

plot_hr <- trips_df_hr %>% ggplot(aes(x=start_hr, y=num_trips))+geom_col()

ggplotly(plot_hr)

```

